services:

  client:
    build: ./client
    ports:
      - "5173:3011"
    env_file:
      - ./client/.env.production
    restart: unless-stopped
    depends_on:
      - server


  server:
    build: ./server
    ports:
      - "3010:3010"
    env_file:
      - ./server/.env.production
    restart: unless-stopped


  actual:
    image: actualbudget/actual-server:25.11.0-alpine
    ports:
      - "5007:5006"
    restart: unless-stopped
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - actual-data:/data

volumes:
  actual-data: